In [1]:
import pandas as pd
import numpy as np

In [2]:
movie_df = pd.read_csv("tmdb_5000_movies.csv")
movie_df.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [3]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [4]:
movie_df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [5]:
movie_df = movie_df[['id', 'title', 'genres', 'vote_average', "vote_count", 'popularity', 'keywords', 'overview']]

In [6]:
movie_df.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3        9106  112.312950  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4        2124   43.926995  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [7]:
movie_df[['genres', 'keywords']][:1]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...

In [8]:
from ast import literal_eval

movie_df['genres'] = movie_df['genres'].apply(literal_eval)

In [9]:
movie_df['keywords'] = movie_df['keywords'].apply(literal_eval)

In [10]:
movie_df[['genres', 'keywords']].iloc[0]

genres      [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
keywords    [{'id': 1463, 'name': 'culture clash'}, {'id':...
Name: 0, dtype: object

In [11]:
genres = []
for tmp_genres in movie_df['genres']:
    tmpList = []
    for i in tmp_genres:
        tmpList.append(i['name'])
    genres.append(tmpList)

In [12]:
genres

[['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Crime'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Fantasy', 'Action', 'Adventure'],
 ['Animation', 'Family'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy', 'Action', 'Science Fiction'],
 ['Adventure', 'Action', 'Thriller', 'Crime'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Western'],
 ['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Adventure', 'Action', 'Fantasy'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action', 'Adventure'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Drama', 'Action'],
 ['Drama', 'Romance

In [13]:
movie_df['genres'] = genres

In [14]:
movie_df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                             genres  vote_average  vote_count  \
0     [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                      [Adventure, Fantasy, Action]           6.9        4500   
2                        [Action, Adventure, Crime]           6.3        4466   
3                  [Action, Crime, Drama, Thriller]           7.6        9106   
4              [Action, Adventure, Science Fiction]           6.1        2124   
...                                             ...           ...         ...   
4798                      [Action, Crime, Thriller]           6.6         238   
4799                              [Comedy, Romance]           5.9           5   
4800             [Comedy, Drama, Romance, TV Movie]           7.0           6   
4801                                             []           5.7           7   
4802                                  [Documentary]           6.3          16   

      popularity                                           keywords  \
0     150.437577  [{'id': 1463, 'name': 'culture clash'}, {'id':...   
1     139.082615  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...   
2     107.376788  [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...   
3     112.312950  [{'id': 849, 'name': 'dc comics'}, {'id': 853,...   
4      43.926995  [{'id': 818, 'name': 'based on novel'}, {'id':...   
...          ...                                                ...   
4798   14.269792  [{'id': 5616, 'name': 'united states–mexico ba...   
4799    0.642552                                                 []   
4800    1.444476  [{'id': 248, 'name': 'date'}, {'id': 699, 'nam...   
4801    0.857008                                                 []   
4802    1.929883  [{'id': 1523, 'name': 'obsession'}, {'id': 224...   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4798  El Mariachi just wants to play his guitar and ...  
4799  A newlywed couple's honeymoon is upended by th...  
4800  "Signed, Sealed, Delivered" introduces a dedic...  
4801  When ambitious New York attorney Sam is sent t...  
4802  Ever since the second grade when he first saw ...  

[4803 rows x 8 columns]

In [16]:
# movie_df = movie_df.drop("processed_genres", axis=1)

In [17]:
# 리스트컴프리핸션
genres = []
for i in movie_df['keywords'][0]:
    print(i)

{'id': 1463, 'name': 'culture clash'}
{'id': 2964, 'name': 'future'}
{'id': 3386, 'name': 'space war'}
{'id': 3388, 'name': 'space colony'}
{'id': 3679, 'name': 'society'}
{'id': 3801, 'name': 'space travel'}
{'id': 9685, 'name': 'futuristic'}
{'id': 9840, 'name': 'romance'}
{'id': 9882, 'name': 'space'}
{'id': 9951, 'name': 'alien'}
{'id': 10148, 'name': 'tribe'}
{'id': 10158, 'name': 'alien planet'}
{'id': 10987, 'name': 'cgi'}
{'id': 11399, 'name': 'marine'}
{'id': 13065, 'name': 'soldier'}
{'id': 14643, 'name': 'battle'}
{'id': 14720, 'name': 'love affair'}
{'id': 165431, 'name': 'anti war'}
{'id': 193554, 'name': 'power relations'}
{'id': 206690, 'name': 'mind and soul'}
{'id': 209714, 'name': '3d'}


In [18]:
tmpList = [1,2,3,4,5]
answerList = [i*2 for i in tmpList]

In [19]:
answerList = []
for i in tmpList:
    answerList.append(i*2)

In [20]:
[i['name'] for i in movie_df['keywords'][0]]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [21]:
movie_df['keywords'] = movie_df['keywords'].apply(lambda x: [i['name'] for i in x])

In [22]:
# 예시
tmpList = ['안녕', '하세요']
" ".join(tmpList)

'안녕 하세요'

In [23]:
movie_df['genres'] = movie_df['genres'].apply(lambda x: " ".join(x))

In [24]:
movie_df['keywords'] = movie_df['keywords'].apply(lambda x: " ".join(x))

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(min_df=1, ngram_range=(1,2))
genres_mat = count_vect.fit_transform(movie_df['genres'])

In [26]:
genres_mat.shape

(4803, 276)

In [27]:
len(movie_df)

4803

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

genres_sim = cosine_similarity(genres_mat, genres_mat)
genres_sim[:2]

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ]])

In [29]:
genres_sim.argsort()[:, ::-1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

In [30]:
genres_sim_sorted_ind = genres_sim.argsort()[:, ::-1]
print(genres_sim_sorted_ind[:1])

[[   0 3494  813 ... 3038 3037 2401]]


In [31]:
def find_sim_move(df, sorted_ind, title_name, top_n=10):

    title_movie = df[df["title"] == title_name]

    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, : top_n]

    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]

In [32]:
simliar_movies = find_sim_move(movie_df, genres_sim_sorted_ind, "The Godfather", 10)
simliar_movies[['title', 'vote_average']]

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [33]:
simliar_movies[['title', 'vote_average']].sort_values(by="vote_average", ascending=False)[:3]

title  vote_average
2731  The Godfather: Part II           8.3
1847              GoodFellas           8.2
3866             City of God           8.1

In [34]:
percetile = 0.6
m = movie_df['vote_count'].quantile(percetile)
c = movie_df['vote_average'].quantile(percetile)
m, c

(370.1999999999998, 6.5)

In [35]:
def weight_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']

    score = ( (v/(v+m))*R ) + ((m/(m+v))*c)

    return score

In [36]:
movie_df['weight_vote_average'] = movie_df.apply(weight_vote_average, axis=1)

In [37]:
movie_df[['title', 'vote_average','weight_vote_average', 'vote_count']].sort_values(by="weight_vote_average", ascending=False)[:10]

title  vote_average  weight_vote_average  vote_count
1881  The Shawshank Redemption           8.5             8.413658        8205
3337             The Godfather           8.4             8.287696        5893
662                 Fight Club           8.3             8.231887        9413
3232              Pulp Fiction           8.3             8.224262        8428
1818          Schindler's List           8.3             8.158197        4329
3865                  Whiplash           8.3             8.155897        4254
65             The Dark Knight           8.2             8.149133       12002
2294             Spirited Away           8.3             8.141727        3840
809               Forrest Gump           8.2             8.124150        7927
2731    The Godfather: Part II           8.3             8.120301        3338

In [38]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출 
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
# 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출 
    return df.iloc[similar_indexes].sort_values('weight_vote_average', ascending=False)[:top_n]

similar_movies = find_sim_movie(movie_df, genres_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'weight_vote_average']]

title  vote_average  weight_vote_average
2731       The Godfather: Part II           8.3             8.120301
1847                   GoodFellas           8.2             8.020096
3866                  City of God           8.1             7.828816
1663  Once Upon a Time in America           8.2             7.762715
883           Catch Me If You Can           7.7             7.593345
281             American Gangster           7.4             7.222038
4041              This Is England           7.4             6.945581
1243                 Mean Streets           7.2             6.837668
1149              American Hustle           6.8             6.765045
2839                     Rounders           6.9             6.717004