In [1]:
# 라이브러리 불러오기
import pandas as pd

In [2]:
# 데이터 확인해보기
df = pd.read_csv('appreply.csv') # index_col=0
df.head()

Unnamed: 0                                               text  score
0           0                                                NaN      4
1           1                                                NaN      5
2           2                                                NaN      1
3           3  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
4           4  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5

In [3]:
df = df.iloc[3:]
df

Unnamed: 0                                               text  score
3              3  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
4              4  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
5              5  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
6              6  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
7              7  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3
...          ...                                                ...    ...
998          998  갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...      1
999          999  기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...      3
1000        1000  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...      3
1001        1001  취소 됐으면 적어도 전화 주는 제도는 있어야하는거 아닌가요? 주문해놓고 다른거 하는...      1
1002        1002  배달의 민족 참 잘 사용하고 있어요. 별 다섯 개를 드리고 싶지만 한 가지 아쉬운 ...      4

[1000 rows x 3 columns]

In [4]:
df = df.reset_index()
df

index  Unnamed: 0                                               text  \
0        3           3  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...   
1        4           4  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...   
2        5           5  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...   
3        6           6  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...   
4        7           7  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...   
..     ...         ...                                                ...   
995    998         998  갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...   
996    999         999  기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...   
997   1000        1000  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...   
998   1001        1001  취소 됐으면 적어도 전화 주는 제도는 있어야하는거 아닌가요? 주문해놓고 다른거 하는...   
999   1002        1002  배달의 민족 참 잘 사용하고 있어요. 별 다섯 개를 드리고 싶지만 한 가지 아쉬운 ...   

     score  
0        4  
1        5  
2        1  
3        2  
4        3  
..     ...  
995      1  
996      3  
997      3  
998      1  
999      4  

[1000 rows x 4 columns]

In [5]:
df = df.drop(columns=['index','Unnamed: 0'])
df

text  score
0    배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
1    내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
2    검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
3    배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
4    최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3
..                                                 ...    ...
995  갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...      1
996  기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...      3
997  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...      3
998  취소 됐으면 적어도 전화 주는 제도는 있어야하는거 아닌가요? 주문해놓고 다른거 하는...      1
999  배달의 민족 참 잘 사용하고 있어요. 별 다섯 개를 드리고 싶지만 한 가지 아쉬운 ...      4

[1000 rows x 2 columns]

In [7]:
# 라이브러리 불러오기
from konlpy.tag import Mecab
import re
from tqdm import tqdm

In [8]:
mecab = Mecab(dicpath="c:/mecab/mecab-ko-dic")

In [10]:
def tokenize_text(text):
    text = re.sub(r'[^ㄱ-ㅣ가-힣\s]', '', text)

    mecab_morphs = mecab.pos(text)

    words = []
    for word, pos in mecab_morphs:
        if pos in ['VA', 'VV', 'NNG', 'NNP']:
            words.append(word)

    word_str = '을 '.join(words)
    return word_str

In [11]:
token_list = []

for temp in tqdm(df['text']):
    token_list.append(tokenize_text(temp))


100%|██████████| 1000/1000 [00:00<00:00, 1717.64it/s]


In [12]:
token_list

['배달을 민족을 주문을 리뷰을 참고을 건을 사항을 있을 신순을 별점을 주문을 하을 메뉴을 특정을 메뉴을 리뷰을 확인을 있을 기능을 있을 좋을 같을 메뉴을 검색을 기능을 리뷰을 특정을 메뉴을 검색을 기능을 필요을 주문을 수을 많을 메뉴을 리뷰을 보을 드래그을 시간을 소요을 효율을 발생을 긍정을 검토을 좋을 같',
 '주문을 과거을 목록을 검색을 기능을 있을 좋을 가게을 기억을 있을 맛있을 먹을 맞을 알을 찾을 어렵을 먹을 메뉴을 검색을 가능을 좋을 예을 들을 곱창을 치을 과거을 곱창을 목록을 뜨을 가게을 리뷰을 창을 리뷰을 보을 좋을 같',
 '검색을 화면을 전체을 배달을 포장을 탭을 배달을 탭을 스크롤을 내리을 때을 아래을 스크롤을 왼쪽을 오른쪽을 넘어가을 전체을 탭을 포장을 탭을 보을 되을 불편을 검색을 후을 배달을 탭을 포장을 탭을 마트을 탭을 선택을 좌우을 넘기을 되을 되을 그러을 스크롤을 때을 왼쪽을 넘어가을 전체을 탭을 가을 되을 불편',
 '배달을 팁을 낮을 순을 정렬을 가게을 위을 지역을 추가을 배을 달료을 있을 별도을 체크을 되을 결국을 배달을 팁을 원을 넘을 이상을 시키을 배달을 팁을 원을 장난을 결국을 가격을 대별을 금액을 체크을 배달을 팁을 별도을 받을 확인',
 '최근을 업데이트을 안드로이드을 사양을 정도을 되을 같을 배민을 플을 실행을 업데이트을 하을 나오을 업데이트을 누르을 업데이트을 진행을 되을 열을 나오을 열을 누르을 업데이트을 나오을 무한을 반복을 삭제을 설치을 환경을 설정을 같을 증상을 같을 증상을 보이을 글을 보을 이번을 업데이트을 관련을 파일을 확인을 필요을 참고을 사양을 높을 폰을 되을 보을 핸드폰을 사양을 문제을 이번을 업데이트을 있',
 '찜을 매장을 구분을 개선을 독점을 앱을 치을 결제을 관련을 부분을 앱을 구성을 단순을 배민을 페이을 사용을 절차을 힘들을 쓰을 찜을 매장을 한식을 양식을 중식을 카페을 업종을 구분을 ㄱ을 ㄴ을 ㄷ을 순을 되을 찜을 매장을 이름을 없을 찾을 검색을 주문을 목록을 찾',
 '앱을 실행을

In [13]:
corpus_list = []

for index in range(len(token_list)):
    corpus = token_list[index]
    if len(set(corpus.split())) < 3:
        corpus_list.append(corpus)

corpus_list

for corpus in corpus_list:
    token_list.remove(corpus)


print(len(token_list))

998


In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

# CountVectorizer를 사용하여 텍스트 데이터를 피처 벡터로 변환
# max_df: 단어가 너무 자주 등장하면 무시 (0.1 이상인 경우 무시)
# max_features: 최대 피처 수는 1000
# min_df: 최소 문서 빈도 (2 이상인 경우 포함)
# ngram_range: 1-그램과 2-그램을 고려
count_vectorizer = CountVectorizer(max_df=0.1, max_features=1000, min_df=2, ngram_range=(1, 2))

# 텍스트 데이터를 피처 벡터로 변환
feat_vect = count_vectorizer.fit_transform(token_list)
print(feat_vect.shape)  # 피처 벡터의 크기 출력
print(count_vectorizer.vocabulary_)  # 피처 이름과 인덱스를 포함한 어휘 출력
#feat_vect.toarray()

(998, 1000)
{'민족을': np.int64(308), '참고을': np.int64(824), '건을': np.int64(45), '사항을': np.int64(442), '신순을': np.int64(520), '별점을': np.int64(380), '특정을': np.int64(894), '확인을': np.int64(985), '필요을': np.int64(936), '수을': np.int64(492), '소요을': np.int64(482), '효율을': np.int64(994), '발생을': np.int64(326), '검토을': np.int64(55), '배달을 민족을': np.int64(340), '민족을 주문을': np.int64(311), '건을 사항을': np.int64(46), '사항을 있을': np.int64(443), '주문을 하을': np.int64(788), '하을 메뉴을': np.int64(948), '특정을 메뉴을': np.int64(895), '메뉴을 리뷰을': np.int64(276), '확인을 있을': np.int64(986), '있을 기능을': np.int64(690), '기능을 있을': np.int64(101), '좋을 같을': np.int64(758), '메뉴을 검색을': np.int64(275), '검색을 기능을': np.int64(50), '리뷰을 보을': np.int64(236), '과거을': np.int64(81), '목록을': np.int64(292), '기억을': np.int64(109), '맛있을': np.int64(262), '맞을': np.int64(265), '알을': np.int64(547), '찾을': np.int64(828), '어렵을': np.int64(561), '가능을': np.int64(9), '예을': np.int64(599), '들을': np.int64(211), '치을': np.int64(861), '뜨을': np.int64(220), '창을': np.int64(826), '좋을 가게을'

In [16]:
# Latent Dirichlet Allocation (LDA) 모델 생성
# n_components: 추출할 토픽 수는 5
lda = LatentDirichletAllocation(n_components=5)
lda.fit(feat_vect)  # 피처 벡터에 LDA 모델을 피팅

LatentDirichletAllocation(n_components=5)

In [17]:
# 첫 번째 토픽의 600번째 피처에 대한 가중치 출력
lda.components_[0][600]

np.float64(0.20210187095404217)

In [18]:
# 첫 번째 토픽에서 가장 높은 가중치를 가지는 상위 10개 단어의 인덱스 출력
lda.components_[0].argsort()[::-1][0:10]

array([225, 982, 374, 605, 668, 996, 299, 220,  15, 445])

In [19]:
# 모든 토픽에 대한 가중치 행렬 출력
lda.components_

array([[ 0.20080766,  0.20057513,  0.20048555, ..., 23.18260769,
         8.19930891,  0.20029548],
       [ 0.20000352,  0.20296443,  0.20000178, ...,  0.2012266 ,
         0.20030336,  1.71871582],
       [ 3.19954935,  6.14396443,  0.20164504, ...,  1.21530522,
         0.20000174,  0.20124916],
       [ 3.19670536,  4.25127217,  9.19766861, ...,  0.20013224,
         0.20038392, 18.67902703],
       [ 0.20293412,  0.20122385,  0.20019902, ...,  0.20072824,
         0.20000207,  0.2007125 ]])

In [20]:
def display_topic(model, feature_names, num_top_words):
    # 모델의 각 토픽에 대해 반복
    for topic_index, topic in enumerate(model.components_):
        print('Topic ', topic_index + 1)  # 현재 토픽 번호 출력
        # 각 토픽에서 단어 가중치를 내림차순으로 정렬하여 인덱스를 반환
        topic_word_indexes = topic.argsort()[::-1]
        # 상위 num_top_words 개의 단어 인덱스를 선택
        top_index = topic_word_indexes[0:num_top_words]
        print(top_index)  # 상위 단어 인덱스 출력
        # 상위 단어 인덱스를 사용하여 실제 단어를 추출
        feature_concat = [feature_names[i] for i in top_index]
        print(feature_concat)  # 상위 단어 출력

# CountVectorizer에서 추출한 피처 이름을 가져옴
feature_names = count_vectorizer.get_feature_names_out()
# LDA 모델을 사용하여 각 토픽에서 상위 10개 단어 출력
display_topic(lda, feature_names, 10)

Topic  1
[225 982 374 605 668 996 299 220  15 445]
['로그인을', '화면을', '번호을', '오류을', '인증을', '후을', '문제을', '뜨을', '가입을', '삭제을']
Topic  2
[107  72  34 464 511 441 335 308 340 630]
['기사을', '고객을', '개선을', '서비스을', '시스템을', '사진을', '배달을 기사을', '민족을', '배달을 민족을', '위치을']
Topic  3
[897 351 163 366 442 625 653  96 620 162]
['팁을', '배달을 팁을', '달비을', '배을 달비을', '사항을', '원을', '이상을', '금액을', '요청을', '달료을']
Topic  4
[828 101 817 851 276   9 503 737 690 207]
['찾을', '기능을 있을', '찜을', '추가을', '메뉴을 리뷰을', '가능을', '스크롤을', '점을', '있을 기능을', '들어가을']
Topic  5
[857 916 985 786  72 478 573 982 865 587]
['취소을', '포장을', '확인을', '주문을 취소을', '고객을', '센터을', '업체을', '화면을', '카드을', '연결을']


In [22]:
import pyLDAvis.lda_model

pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda,feat_vect,count_vectorizer)
pyLDAvis.display(vis)

In [23]:
# LDA 모델을 사용하여 각 문서의 토픽 분포를 추정
# feat_vect: 문서-단어 행렬 (CountVectorizer로 변환된 피처 벡터)
# sent_topic: 문서-토픽 행렬, 각 행은 문서별 토픽 분포를 나타냄
sent_topic = lda.transform(feat_vect)
sent_topic  # 문서-토픽 분포 행렬 출력

array([[0.00576135, 0.00592746, 0.32065629, 0.66188898, 0.00576592],
       [0.00755127, 0.00748837, 0.00745507, 0.97001289, 0.0074924 ],
       [0.00536186, 0.00531841, 0.00528529, 0.28277652, 0.70125793],
       ...,
       [0.01013103, 0.53754914, 0.01029074, 0.43195905, 0.01007003],
       [0.00879557, 0.00899016, 0.00880202, 0.21457425, 0.75883799],
       [0.00504672, 0.00518766, 0.00503972, 0.43724526, 0.54748064]])

In [24]:
# 문서별 가장 관련성이 높은 토픽과 그 확률을 저장할 리스트 초기화
sent_topic_per_list = []

# 각 문서에 대해 반복
for temp in range(sent_topic.shape[0]):
    # 해당 문서에서 가장 높은 확률을 가진 토픽의 인덱스를 찾음
    sent_topic_list = sent_topic[temp].argmax()
    # 해당 문서에서 가장 높은 확률 값
    topic_per = sent_topic[temp].max()
    # 문서 번호, 가장 높은 확률을 가진 토픽 인덱스, 확률을 리스트에 추가
    sent_topic_per_list.append([temp, sent_topic_list, topic_per])

# 리스트를 데이터프레임으로 변환, 컬럼명은 'no', '토픽번호', '확률'
topic_df = pd.DataFrame(sent_topic_per_list, columns=['no', '토픽번호', '확률'])

# 기존 데이터프레임 df와 문서별 토픽 정보를 조인 (병합)
doc_topic_df = topic_df.join(df)

# 최종 데이터프레임 출력
doc_topic_df

no  토픽번호        확률                                               text  \
0      0     3  0.661889  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...   
1      1     3  0.970013  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...   
2      2     4  0.701258  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...   
3      3     2  0.978066  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...   
4      4     0  0.625145  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...   
..   ...   ...       ...                                                ...   
993  993     0  0.975662  제가 배민어플 거의 매달 vip 실적 오를만큼 엄청 이용하는데요 주문시키면 매장 전...   
994  994     1  0.770204  배달의 민족 사용자 경험이 갈수록 하락하고 있는 것 같음. 개선되거나 발전되는 느낌...   
995  995     1  0.537549  갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...   
996  996     4  0.758838  기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...   
997  997     4  0.547481  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...   

     score  
0        4  
1        5  
2        1  
3        2  
4        3  
..     ...  
993      1  
994      1  
995      1  
996      3  
997      3  

[998 rows x 5 columns]

In [25]:
doc_topic_df.groupby('토픽번호')['no'].count()

토픽번호
0    198
1    206
2    206
3    223
4    165
Name: no, dtype: int64

In [26]:
doc_topic_df[doc_topic_df['토픽번호']==2].sort_values(by='확률',ascending=False)

no  토픽번호        확률                                               text  \
111  111     2  0.986009  앱 정말 잘 쓰고 있습니다. 그런데 한가지 건의 드려도 될까요? 배달팁 낮은 순서로...   
200  200     2  0.981248  배달료순으로 정렬하는 기능이 있는데, 가게마다 배달료가 단일이 아니고 0~4,000...   
505  505     2  0.980144  배달비 진짜 선넘네. 그렇다고 요기요처럼 패스가 있는것도 아니고 할인쿠폰을 주는것도...   
84    84     2  0.979871  요즘 배달팁을 "0원~"으로 보이게 설정해놓는 가게들이 너무 많습니다. 실제로 주문...   
987  987     2  0.978622  잘 사용하고잇습니다~ 놀러가서도 사용할수잇어서 편하구요ㅎㅎ 다만..제가 친구네서 시...   
..   ...   ...       ...                                                ...   
847  847     2  0.381362  네이버 로그인은 있으면서 인증에서 넘어가지도 않고 이래저래 인증 다하고 주문하니 배...   
176  176     2  0.380909  어플 평점이 엄청 낮네요.. 저는 음식점 배달보다 B마트를 넘넘 잘 애용하고 있습니...   
964  964     2  0.376829  햄버거를 주문했고 결제는 되었는데 주문확인중이라는 창이 떴지만 카톡이 오지 않았습니...   
380  380     2  0.361128  할인 쿠폰이 적용 안 되는 경우가 종종 있는데 이건 언제 고쳐지는건가요? 고객센터에...   
961  961     2  0.319058  일방적이며 잦은 주문 취소 및 불안정적인 서버 운영으로 쉽게 터져버리는 서비스. 해...   

     score  
111      5  
200      1  
505      1  
84       2  
987      4  
..     ...  
847      1  
176      5  
964      1  
380      1  
961      1  

[206 rows x 5 columns]