In [1]:
import numpy as np

# 벡터 정의
a = np.array([1, 2])
b = np.array([3, 4])

# 벡터 덧셈
c = a + b
# 결과: [4 6]
print("벡터 덧셈:", c)

# 벡터 뺄셈
d = a - b
# 결과: [-2 -2]
print("벡터 뺄셈:", d)

# 스칼라 곱셈
e = 2 * a
# 결과: [2 4]
print("스칼라 곱셈:", e)

# 벡터 내적 (dot product)
f = np.dot(a, b)
# 결과: 11
print("벡터 내적:", f)

벡터 덧셈: [4 6]
벡터 뺄셈: [-2 -2]
스칼라 곱셈: [2 4]
벡터 내적: 11


In [2]:
import numpy as np

# 행렬 정의
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 행렬 덧셈
C = A + B
# 결과: [[ 6  8]
#        [10 12]]
print("행렬 덧셈:\n", C)

# 행렬 뺄셈
D = A - B
# 결과: [[-4 -4]
#        [-4 -4]]
print("행렬 뺄셈:\n", D)

# 스칼라 곱셈
E = 2 * A
# 결과: [[2 4]
#        [6 8]]
print("스칼라 곱셈:\n", E)

# 행렬 곱셈 (matrix multiplication)
F = np.dot(A, B)
# 결과: [[19 22]
#        [43 50]]
print("행렬 곱셈:\n", F)

# 전치 행렬 (transpose)
G = np.transpose(A)
# 결과: [[1 3]
#        [2 4]]
print("전치 행렬:\n", G)

행렬 덧셈:
 [[ 6  8]
 [10 12]]
행렬 뺄셈:
 [[-4 -4]
 [-4 -4]]
스칼라 곱셈:
 [[2 4]
 [6 8]]
행렬 곱셈:
 [[19 22]
 [43 50]]
전치 행렬:
 [[1 3]
 [2 4]]


In [3]:
import numpy as np

# 행렬 정의
A = np.array([[1, 2], [3, 4]])

# 행렬식 (determinant)
det_A = np.linalg.det(A)
# 결과: -2.0000000000000004
print("행렬식:", det_A)

# 역행렬 (inverse)
inv_A = np.linalg.inv(A)
# 결과: [[-2.   1. ]
#        [ 1.5 -0.5]]
print("역행렬:\n", inv_A)

# 역행렬과 원래 행렬을 곱하면 단위 행렬이 됨
I = np.dot(A, inv_A)
# 결과: [[ 1.0000000e+00  0.0000000e+00]
#        [ 0.0000000e+00  1.0000000e+00]]
print("단위 행렬:\n", I)

행렬식: -2.0000000000000004
역행렬:
 [[-2.   1. ]
 [ 1.5 -0.5]]
단위 행렬:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
